version: 2

models:
  - name: stg_local_bike_production__brands
    description: "This model contains the list of brands sold by local bike in their stores"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "Naming each brand and linking them to a unique brand id."



  - name: stg_local_bike_production__categories
    description: "This model contains the list of categories sold by local bike in their stores"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
            - unique
            - not_null
      - name: category_name
        description: "Naming each category and linking them to a unique category id."



  - name: stg_local_bike_production__products
    description: "This model contains information about the each product sold by local bike in their stores"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: product_name
        description: "Naming each product and linking them to a unique product id."
      - name: brand_id
        description: "Foreign key linking the product to the corresponding brand."
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_local_bike_production__products
              to: ref('stg_local_bike_production__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product to the corresponding category."
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_local_bike_production__products
              to: ref('stg_local_bike_production__category')
              field: category_id
      - name: model_year
        description: "The year of the product's model."
      - name: list_price
        description: "The price of each product."


  - name: stg_local_bike_production__stocks
    description: "This model contains information about the quantity of products available in each of local bike stores"
    columns:
      - name: stock_id
        description: "Primary key for this table."
        tests:
          - unique
          - not_null
      - name: store_id
        description: "Foreign key linking the stock to the corresponding store."
        tests:
          - relationships:
            name: store_id_foreign_key_in_stg_local_bike_production__stocks
            to: ref('stg_local_bike_sales__stores')
            field: store_id
      - name: product_id
        description: "Foreign key linking each product id to the corresponding description."
        tests: 
          - relationships:
            name: product_id_foreign_key_in_stg_local_bike_production__stocks
            to: ref('stg_local_bike_production__products')
            field: product_id
      - name: quantity
        description: "The quantity of each product in each store."


  - name: stg_local_bike_sales__customers
    description: "This model contains customer related informations including their name, email adress, phone number etc."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "The first name of each customer."
      - name: last_name
        description: "The last name of each customer."
      - name: phone
        description: "Customers' phone number"
      - name: email
        description: "Customers' email address"
      - name: street
        description: "Customers' street address"
      - name: city
        description: "Customers' city name"
      - name: state
        description: "Customers' state name"
      - name: zip_code
        description: "Customers' zip code"


  - name: stg_local_bike_sales__order_items
    description: "This model contains information about each item included in an order, including its price, quantity, shipping cost etc."
    columns:
      - name: order_item_id
        description: "Primary key for this table."
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key linking each order id to the corresponding order."
        tests: 
          - relationships:
            name: order_id_foreign_key_in_stg_local_bike_sales__order_items
            to: ref('stg_local_bike_sales__orders')
            field: order_id
      - name: item_id
        description: "Unique identifier of each item."
      - name: product_id
        description: "Foreign key linking each product to its description."
        tests: 
          - relationships:
            name: product_id_foreign_key_in_stg_local_bike_sales__order_items
            to: ref('stg_local_bike_production__products')
            field: product_id
      - name: quantity
        description: "The quantity of each item in the order."
      - name: list_price
        description: "The price of each item in the order."
      - name: discount
        description: "The amount of discount of each item"


  - name: stg_local_bike_sales__orders
    description: "This model contains information about each order including its status, date, store linked to it, etc."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests: 
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key linking each order to the customer who placed it."
        tests: 
          - relationships:
            name: customer_id_foreign_key_in_stg_local_bike_sales__orders
            to: ref('stg_local_bike_sales__customers')
            field: customer_id
      - name: order_status
        description: "The status of the order."
      - name: order_date
        description: "The day the order was placed."
      - name: required_date
        description: "The day the order should be at the store."
      - name: shipped_date
        description: "The day the order is shipped."
      - name: store_id
        description: "Foreign key linking each order to the store from which it was shipped."
        tests: 
          - relationships:
            name: store_id_foreign_key_in_stg_local_bike_sales__orders
            to: ref('stg_local_bike_sales__stores')
            field: store_id
      - name: staff_id
        description: "Foreign key linking each seller to its description/informations."
        tests: 
          - relationships:
            name: staff_id_foreign_key_in_stg_local_bike_sales__orders
            to: ref('stg_local_bike_sales__staffs')
            field: staff_id


  - name: stg_local_bike_sales__staffs
    description: "This model contains information about each staff member including theirs names, phone number, store_id, etc."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests: 
          - unique
          - not_null
      - name: first_name
        description: "The staff member's first name."
      - name: last_name
        description: "The staff member's last name."
      - name: email
        description: "The staff member's email address."
      - name: phone
        description: "The staff member's phone number."
      - name: active
        description: "Wether or not the staff member is active."
      - name: store_id
        description: "Id number of the staff member's store."
      - name: manager_id
        description: "Id number of the staff member's manager."


  - name: stg_local_bike_sales__stores
    description: "This model contains information about each store including its name, address, id, etc."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each order."
        tests: 
          - unique
          - not_null
      - name: store_name
        description: "The store's name."
      - name: phone
        description: "The store's phone number."
      - name: email
        description: "The store's email."
      - name: street
        description: "The store's street address."
      - name: city
        description: "The store's city."
      - name: state
        description: "The store's state."
      - name: zip_code
        description: "The store's zip code."