version: 2

sources:
  - name: local_bike_production
    schema: local_bike_production
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks
      
  - name: local_bike_sales
    schema: local_bike_sales
    tables:
      - name: customers
      - name: order_items
      - name: orders
      - name: staffs
      - name: stores

